### ISSUE TITLE
CurvesId values for other curves.

### ISSUE THREAD

**Issue by ndcroos** [LedgerHQ/ledger-nanos-sdk#20]
To use a function like `ec_init_key` in `ecc.rs`, a `CurvesId` argument is needed.
However, the enum contains only a value for the curve `Secp256k1`.
Could other curves also be added to this enum?
I would like a value for the curve `Ed25519 (CX_CURVE_Ed25519)`, but other curves could also be added.

See:
https://github.com/LedgerHQ/ledger-nanos-sdk/blob/0d676b552f81d00b96bd9a09f28565086a5efb1f/src/ecc.rs#L5

**Comment by sunny-g** [comment]
Any updates on this? Can I open a PR for this `CX_CURVE_Ed25519`?
